version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "building"
          command: |
            make build
            mv extractor.pyz /tmp/

      - persist_to_workspace:
          root: /tmp
          paths:
            - extractor.pyz

  deploy:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp
      - run: go get github.com/c4milo/github-release
      - run: github-release vscreen/extractor `date +%G-%m-%d` master "" "/tmp/extractor.pyz"

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - deploy:
          requires:
            - build
  automated:
    jobs:
      - build
      - deploy:
          requires:
            - build
